export const AUTH_USER = "AUTH_USER";
export const GET_BRANDS = "GET_BRANDS";
export const GET_PRODUCTS_BY_ARRIVAL = "GET_PRODUCTS_BY_ARRIVAL";
export const GET_PRODUCTS_BY_SALES = "GET_PRODUCTS_BY_SALES";
export const GET_WOODS = "GET_WOODS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
